# This is the default format.
# For more see: https://github.com/mojombo/jekyll/wiki/Permalinks
permalink: /:categories/:year/:month/:day/:title

exclude: [".rvmrc", ".rbenv-version", "ReadMe.md", "Rakefile", "changelog.md", "License.md"]
highlighter: rouge

# Themes are encouraged to use these universal variables
# so be sure to set them if your theme uses them.
#
title : Noah Chrein
author :
  name : Noah Chrein
  github : nopounch

production_url : https://nopounch.github.io


markdown: kramdown


JB :
  version : 0.3.0
  BASE_PATH : https://nopounch.github.io

  archive_path: nil
  categories_path : nil
  tags_path : nil
  atom_path : nil
  rss_path : nil

  comments :
    provider : false

  analytics :
    provider : false

  sharing :
    provider : false

theme: jekyll-theme-cayman